/* global Game */
window.PVZ_CONFIG = {
  ROWS: 5,
  COLS: 9,
  CELL_W: 82,
  CELL_H: 92,
  GRID_X: 260,
  GRID_Y: 28,
  HOUSE_X: 32,
  MOWER_W: 36,
  STARTING_SUN: 50,
  SUN_VALUE: 25,
  SKY_SUN_MIN: 6,
  SKY_SUN_MAX: 11,
  TOTAL_WAVES: 8,
  ZOMBIES_BASE: 4,
  ZOMBIES_PER_WAVE: 2,
  SPAWN_GAP_MIN: 2.2,
  SPAWN_GAP_MAX: 4.5,
  PEA_DAMAGE: 20,
  PEA_SPEED: 340,
  ZOMBIE_DAMAGE_PER_S: 45,
  PLANTS: {
    sunflower: {
      name: "Sunflower",
      cost: 50,
      hp: 80,
      sunInterval: 7.4,
      sunJitter: 2,
    },
    peashooter: {
      name: "Peashooter",
      cost: 100,
      hp: 80,
      shootInterval: 1.45,
    },
    wallnut: {
      name: "Wall-nut",
      cost: 50,
      hp: 400,
    },
  },
  ZOMBIE: {
    hp: 200,
    speed: 24,
    bodyW: 46,
    bodyH: 78,
  },
};
